version: '3'

services:
  jira:
    depends_on:
      - postgresql
    image: jira:7.12.3
    networks:
      - jiranet
    volumes:
      - ./jira-data2:/var/atlassian/jira
    ports:
      - '80:8080'
    environment:
      - 'JIRA_DATABASE_URL=postgresql://jira@postgresql/jiradb'
      - 'JIRA_DB_PASSWORD=jellyfish'
      - 'SETENV_JVM_MINIMUM_MEMORY=384m'
      - 'SETENV_JVM_MAXIMUM_MEMORY=1g'
      - 'JIRA_PROXY_NAME='
      - 'JIRA_PROXY_PORT='
      - 'JIRA_PROXY_SCHEME='
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    labels:
      com.blacklabelops.description: "Atlassian Jira"
      com.blacklabelops.service: "jira"

  postgresql:
    image: postgres:9.4
    #user: root
    networks:
      - jiranet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jira'
      - 'POSTGRES_PASSWORD=jellyfish'
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    labels:
      com.blacklabelops.description: "PostgreSQL Database Server"

volumes:
#  data:
#    external:
#      name: jira_data
  postgresqldata:
    external: false
networks:
  jiranet:
    driver: bridge